### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by njumaen**
* fixed on-error ( removed the doubequotes at end of line)

* added counting of errors to statistics

### CODE REVIEW

**Comment by multiduplikator** [comment]
> * fixed on-error ( removed the doubequotes at end of line)
> * added counting of errors to statistics

I am not sure if it is worth it to add error handling.

The biggest concern I have with it that we break backwards compatibility, since ":do {} on-error" only works with ROS 6.2 and upwards. And there are still thousands of devices that stay on 6.1.x for performance and wireless stability reasons...

And since logging to console is off during update, the ":put" message on error will not be in the logs...not sure if error is also disabled, or only info...

**Comment by njumaen** [comment]
I had (rarely) a broken scrip running so I've added the on-error part to be safe 

:put was for debuging only so it can be removed.

Version dependency could be solve with  a comment ;-)

**Comment by multiduplikator** [comment]
> 



> I had (rarely) a broken scrip running so I've added the on-error part to be safe
> 
> :put was for debuging only so it can be removed.
> 
> Version dependency could be solve with a comment ;-)

All right then :)

**Comment by multiduplikator** [comment]
> I had (rarely) a broken scrip running so I've added the on-error part to be safe
> 
> :put was for debuging only so it can be removed.
> 
> Version dependency could be solve with a comment ;-)



> I had (rarely) a broken scrip running so I've added the on-error part to be safe
> 
> :put was for debuging only so it can be removed.
> 
> Version dependency could be solve with a comment ;-)



> I had (rarely) a broken scrip running so I've added the on-error part to be safe
> 
> :put was for debuging only so it can be removed.
> 
> Version dependency could be solve with a comment ;-)

I will close this

**Comment by multiduplikator** [comment]
Updating the script with proper version detection...

**Pull request closed without merging**
